# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'voxGuru' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  pod 'React', :path => '../node_modules/react-native'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Firestore'
  pod 'react-native-branch', path: '../node_modules/react-native-branch'
  pod 'Branch-SDK', path: '../node_modules/react-native-branch/ios'

  

    
end
