# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'voxGuru' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  pod 'React', :path => '../node_modules/react-native'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Firestore'
  pod 'react-native-branch', path: '../node_modules/react-native-branch'
  pod 'Branch-SDK', path: '../node_modules/react-native-branch/ios'


  # Pods for voxGuru

  target 'voxGuru-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
   

  end

  target 'voxGuruTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'voxGuru-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for voxGuru-tvOS
  
end
